(()=>{
'use strict';
const WA='212640008930';let db=null;
const S={project:null,c:{},recs:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dh=n=>new Intl.NumberFormat('fr-MA',{maximumFractionDigits:0}).format(n)+' DH';
const names={network:'Installation réseau',gaming:'PC Gaming',upgrade:'Upgrade PC',office:'Équipement de bureau',printing:'Installation imprimante',storage:'Ajout de stockage'};
const pool=(g,p=()=>true)=>(db.products||[]).filter(x=>(x.groups||[]).includes(g)&&p(x)).sort((a,b)=>(a.price||1e9)-(b.price||1e9));
const best=(g,p=()=>true)=>pool(g,p).slice(0,3);
const product=id=>db.products.find(x=>x.id===id);
function step(n){$$('.quote-step').forEach((x,i)=>x.classList.toggle('is-active',i===n));}
function field(l,id,h,help=''){return `<div class="field"><label for="${id}">${l}</label>${h}${help?`<small>${help}</small>`:''}</div>`}
async function load(){const r=await fetch('knowledge/pricing.json',{cache:'no-store'});if(!r.ok)throw Error('prices');db=await r.json();projects()}
function projects(){step(0);$('#quote-view').innerHTML=`<div class="quote-view"><div class="view-kicker">27SYS / CONFIGURATEUR</div><h2 class="view-title">Quel projet souhaitez-vous réaliser ?</h2><p class="view-sub">Décrivez votre objectif plutôt que de choisir du matériel au hasard. Le moteur détermine les composants utiles, puis compare les références suivies au Maroc.</p><div class="project-grid">
<button class="project-card" data-p="network"><b>01</b><strong>🌐 Installer un réseau</strong><span>Routeur, switch, Wi‑Fi, Ethernet et segmentation.</span></button>
<button class="project-card" data-p="gaming"><b>02</b><strong>🎮 Monter un PC Gaming</strong><span>Composants adaptés à votre résolution, jeux et budget.</span></button>
<button class="project-card" data-p="upgrade"><b>03</b><strong>⬆ Upgrader un PC</strong><span>Choisissez le composant à changer et obtenez plusieurs options.</span></button>
<button class="project-card" data-p="office"><b>04</b><strong>🏢 Équiper un bureau</strong><span>Postes, réseau, Wi‑Fi, impression et onduleur.</span></button>
<button class="project-card" data-p="printing"><b>05</b><strong>🖨 Installer une imprimante</strong><span>Choix guidé selon usage, technologie et couleur.</span></button>
<button class="project-card" data-p="storage"><b>06</b><strong>💾 Ajouter du stockage</strong><span>SSD NVMe ou SATA selon l'objectif.</span></button></div></div>`;$$('[data-p]').forEach(b=>b.onclick=()=>{S.project=b.dataset.p;S.c={};S.recs=[];questions()})}
function questions(){step(1);let b='';
if(S.project==='network')b=`<div class="form-grid">${field('TYPE DE RÉSEAU','nt',`<select id="nt"><option value="home">Maison</option><option value="office" selected>Petit bureau / PME</option><option value="wifi">Amélioration Wi‑Fi</option><option value="wired">Ethernet filaire</option><option value="hybrid">Ethernet + Wi‑Fi</option></select>`)}${field('ÉQUIPEMENTS FILAIRES','np',`<input id="np" type="number" min="1" max="96" value="8">`)}${field('COUVERTURE WI‑FI','nc',`<select id="nc"><option value="none">Aucun AP supplémentaire</option><option value="small">Petite zone</option><option value="medium" selected>Zone moyenne</option><option value="large">Grande surface</option></select>`)}${field('ROUTEUR','nr',`<select id="nr"><option value="basic">Économique</option><option value="wifi6" selected>Wi‑Fi 6 / polyvalent</option><option value="pro">Plus de capacité</option></select>`)}${field('SEGMENTATION / INVITÉS','ns',`<select id="ns"><option value="no">Non</option><option value="yes">Oui</option><option value="unknown">Je ne sais pas</option></select>`)}${field('CÂBLAGE','nca',`<select id="nca"><option value="0">À mesurer</option><option value="25">25 m</option><option value="50">50 m</option><option value="100">100 m</option><option value="200">200 m</option></select>`)}</div>`;
if(S.project==='gaming')b=`<div class="form-grid">${field('RÉSOLUTION','gr',`<select id="gr"><option value="1080">1080p</option><option value="1440" selected>1440p</option><option value="4k">4K</option></select>`)}${field('USAGE','gu',`<select id="gu"><option value="esport">E‑sport</option><option value="general" selected>Gaming général</option><option value="heavy">AAA / jeux lourds</option></select>`)}${field('BUDGET','gb',`<select id="gb"><option value="6000">≤ 6 000 DH</option><option value="9000" selected>6 000–9 000 DH</option><option value="13000">9 000–13 000 DH</option><option value="high">13 000 DH+</option></select>`)}${field('CONFIGURATION','gn',`<select id="gn"><option value="yes" selected>PC complet</option><option value="no">Je garde certains composants</option></select>`)}</div>`;
if(S.project==='upgrade')b=`<div class="form-grid">${field('COMPOSANT','up',`<select id="up"><option value="gpu">Carte graphique</option><option value="cpu">Processeur</option><option value="ram">RAM</option><option value="ssd">SSD</option><option value="psu">Alimentation</option></select>`)}${field('OBJECTIF','ug',`<select id="ug"><option value="fps">Plus de FPS</option><option value="speed">PC plus rapide</option><option value="capacity">Plus de capacité</option><option value="stability">Stabilité</option></select>`)}${field('PLATEFORME','uf',`<select id="uf"><option value="unknown">Je ne sais pas</option><option value="am4">AMD AM4</option><option value="am5">AMD AM5</option><option value="intel">Intel</option></select>`)}${field('BUDGET MAX','ub',`<select id="ub"><option value="1000">1 000 DH</option><option value="2000" selected>2 000 DH</option><option value="4000">4 000 DH</option><option value="6000">6 000 DH+</option></select>`)}</div>`;
if(S.project==='office')b=`<div class="form-grid">${field('NOMBRE DE POSTES','op',`<input id="op" type="number" min="1" max="96" value="8">`)}${field('TYPE','ot',`<select id="ot"><option value="portable" selected>Portables</option><option value="desktop">PC fixes</option><option value="mixed">Mixte</option></select>`)}${field('WI‑FI','ow',`<select id="ow"><option value="none">Aucun</option><option value="one">1 zone</option><option value="multi" selected>Plusieurs zones</option></select>`)}${field('IMPRESSION','oi',`<select id="oi"><option value="none">Aucune</option><option value="laser" selected>Laser monochrome</option><option value="color">Couleur</option></select>`)}${field('ONDULEUR','ou',`<select id="ou"><option value="none">Aucun</option><option value="one" selected>1 central</option></select>`)}</div>`;
if(S.project==='printing')b=`<div class="form-grid">${field('USAGE','pu',`<select id="pu"><option value="home">Maison</option><option value="office" selected>Bureau</option><option value="volume">Impression fréquente</option></select>`)}${field('TECHNOLOGIE','pt',`<select id="pt"><option value="laser">Laser</option><option value="tank" selected>Réservoir</option></select>`)}${field('COULEUR','pc',`<select id="pc"><option value="mono">Noir & blanc</option><option value="color" selected>Couleur</option></select>`)}</div>`;
if(S.project==='storage')b=`<div class="form-grid">${field('INTERFACE','st',`<select id="st"><option value="nvme" selected>NVMe</option><option value="sata">SATA 2,5\"</option></select>`)}${field('CAPACITÉ','ss',`<select id="ss"><option value="500" selected>~500 Go</option><option value="1000">~1 To</option></select>`)}</div>`;
$('#quote-view').innerHTML=`<div class="quote-view"><div class="view-kicker">27SYS / FILTRAGE TECHNIQUE</div><h2 class="view-title">Définissez votre besoin.</h2><p class="view-sub">Ces réponses permettent d'écarter les produits inadaptés avant de regarder le prix.</p>${b}<div class="quote-actions"><button class="btn" id="back">← Changer de projet</button><button class="btn btn-primary" id="go">Voir les recommandations →</button></div></div>`;$('#back').onclick=projects;$('#go').onclick=build}
function read(){document.querySelectorAll('#quote-view input,#quote-view select').forEach(e=>S.c[e.id]=e.value)}
function build(){read();const c=S.c,r=[];if(S.project==='network'){const n=+c.np||1;const rg=c.nr==='pro'?'router-pro':c.nr==='basic'?'router-basic':'router-wifi6';const rp=best(rg)[0]||best('router-basic')[0];if(rp)r.push({slot:'Routeur',p:rp,why:'Filtré par niveau de capacité.'});const sw=best('switch',x=>(+x.ports||0)>=n+1)[0];if(sw)r.push({slot:'Switch',p:sw,why:`Capacité pour ${n} équipements + marge.`});const aq=c.nc==='large'?2:c.nc==='none'?0:1;const ap=best('access-point')[0];if(aq&&ap)r.push({slot:`Point d'accès × ${aq}`,p:ap,q:aq,why:'Quantité liée à la couverture.'});if(+c.nca)r.push({slot:'Câble Cat6 indicatif',custom:true,q:+c.nca,unit:4,why:'Métrage à confirmer sur site.'})}
if(S.project==='gaming'){const gg=c.gr==='4k'?'gpu-4k':c.gr==='1440'?'gpu-1440':'gpu-1080';const g=best(gg,x=>c.gb==='high'||(+x.min_budget||0)<=+c.gb)[0]||best(gg)[0];const cpu=best('cpu-gaming')[0],ram=best('ram-gaming')[0],ssd=best('ssd-gaming')[0],psu=best('psu-gaming')[0];if(cpu)r.push({slot:'Processeur',p:cpu,why:'Base équilibrée.'});if(g)r.push({slot:'Carte graphique',p:g,why:`Ciblée pour ${c.gr}.`});if(ram)r.push({slot:'RAM',p:ram,why:'Capacité adaptée.'});if(ssd)r.push({slot:'SSD',p:ssd,why:'Stockage système + jeux.'});if(psu)r.push({slot:'Alimentation',p:psu,why:'Marge de puissance.'})}
if(S.project==='upgrade'){const map={gpu:'gpu-upgrade',cpu:'cpu-upgrade',ram:'ram-upgrade',ssd:'ssd-generic',psu:'psu-gaming'};best(map[c.up]||'ssd-generic').forEach((p,i)=>r.push({slot:`${c.up.toUpperCase()} — ${i?'alternative':'prix le plus bas'}`,p,why:'Référence filtrée ; compatibilité finale à valider.'}))}
if(S.project==='office'){const n=+c.op||1,pc=best('laptop-office')[0],rt=best('router-office')[0]||best('router-wifi6')[0],sw=best('switch',x=>(+x.ports||0)>=n+1)[0];if(pc)r.push({slot:`Poste × ${n}`,p:pc,q:n,why:'Profil bureautique.'});if(rt)r.push({slot:'Routeur',p:rt,why:'Base petite entreprise.'});if(sw)r.push({slot:'Switch',p:sw,why:`Pour ${n} postes.`});const aq=c.ow==='multi'?2:c.ow==='one'?1:0,ap=best('access-point')[0];if(aq&&ap)r.push({slot:`Point d'accès × ${aq}`,p:ap,q:aq,why:'Couverture Wi‑Fi.'});if(c.oi==='laser'){const p=best('printer-laser')[0];if(p)r.push({slot:'Imprimante laser',p,why:'Documents bureau.'})}if(c.oi==='color'){const p=best('printer-tank',x=>x.color==='color')[0]||best('printer-tank')[0];if(p)r.push({slot:'Imprimante couleur',p,why:'Réservoir couleur.'})}if(c.ou==='one'){const p=best('ups')[0];if(p)r.push({slot:'Onduleur',p,why:'Protection électrique.'})}}
if(S.project==='printing'){const g=c.pt==='laser'?'printer-laser':'printer-tank';let a=best(g,x=>c.pc==='mono'?x.color==='mono':x.color!=='mono');if(!a.length)a=best(g);a.forEach((p,i)=>r.push({slot:`Imprimante — ${i?'alternative':'meilleur prix compatible'}`,p,why:'Filtrée par technologie et couleur.'}))}
if(S.project==='storage'){const g=c.st==='nvme'?'ssd-nvme':'ssd-sata';best(g).forEach((p,i)=>r.push({slot:`SSD ${c.ss} Go — ${i?'alternative':'meilleur prix'}`,p,why:'Filtré par interface.'}))}
S.recs=r;result()}
function total(){return S.recs.reduce((s,r)=>s+(r.custom?r.q*r.unit:(r.p.price*(r.q||1))),0)}
function text(t){return `PRÉ-DEVIS 27SYS\n\nProjet : ${names[S.project]}\n\n${S.recs.map(r=>r.custom?`• ${r.q} m câble Cat6 = ${dh(r.q*r.unit)}`:`• ${(r.q||1)} × ${r.p.name} = ${dh(r.p.price*(r.q||1))} — ${r.p.source}`).join('\n')}\n\nTOTAL ÉQUIPEMENTS : ${dh(t)}\nInstallation : devis personnalisé après échange avec 27sys.\n\nPrix indicatifs Maroc : disponibilité, vendeur, garantie et référence exacte à confirmer.`}
function result(){step(2);const t=total();$('#quote-view').innerHTML=`<div class="quote-view"><div class="view-kicker">27SYS / PRÉ‑DEVIS</div><h2 class="view-title">Configuration recommandée</h2><p class="view-sub">Le moteur a d'abord déterminé les composants utiles puis retenu les offres les moins chères parmi les références qui passent les filtres du projet.</p><div class="recommendation-summary"><span>PROJET</span><strong>${names[S.project]}</strong><span>TOTAL</span><b>${dh(t)}</b></div><div class="recommendation-list">${S.recs.map(r=>r.custom?`<div class="recommendation-row"><div><span class="rec-slot">${r.slot}</span><strong>${r.q} m</strong><small>${r.why}</small></div><div class="qty-static">× 1</div><div class="rec-price">${dh(r.q*r.unit)}</div></div>`:`<div class="recommendation-row"><div class="rec-product"><span class="rec-slot">${esc(r.slot)}</span><strong>${esc(r.p.name)}</strong><small>${esc(r.why)}</small><div class="rec-tags"><span>${esc(r.p.level||'Compatible')}</span>${r.p.auto_update?'<span>PRIX SUIVI</span>':''}<a href="${esc(r.p.url)}" target="_blank">${esc(r.p.source)} ↗</a></div></div><div class="qty-static">× ${r.q||1}</div><div class="rec-price">${dh(r.p.price*(r.q||1))}</div></div>`).join('')}</div><div class="total-card"><div><b>TOTAL ÉQUIPEMENTS</b><strong>${dh(t)}</strong><p class="install-note"><strong>Installation non incluse.</strong> Déplacement, configuration, main-d'œuvre et métrage réel sont chiffrés par 27sys.</p></div><button class="btn btn-primary" id="wa">Demander le devis d'installation ↗</button></div><div class="quote-actions"><button class="btn" id="edit">← Modifier mon besoin</button><button class="btn btn-blue" id="copy">Copier le pré-devis</button></div><div class="price-note"><strong>Règle :</strong> le moins cher n'est recommandé que s'il passe les filtres techniques. ${esc(db.meta?.note||'')}</div></div>`;$('#edit').onclick=questions;const tx=text(t);$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(tx);$('#copy').textContent='Copié ✓'}catch{prompt('Copiez le pré-devis :',tx)}};$('#wa').onclick=()=>window.open(`https://wa.me/${WA}?text=${encodeURIComponent('Bonjour 27sys,\n\n'+tx+'\n\nJe souhaite connaître le coût d’installation et valider cette configuration.')}`,'_blank')}
load().catch(e=>{$('#quote-view').innerHTML='<div class="tree-empty">Impossible de charger les prix. Rechargez la page ou contactez 27sys sur WhatsApp.</div>';console.error(e)});
})();
