(() => {
  'use strict';
  const WA='212640008930';
  const state={project:null,config:null,items:[]};
  let db=null;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>new Intl.NumberFormat('fr-MA',{maximumFractionDigits:0}).format(n)+' DH';
  async function load(){const r=await fetch('knowledge/pricing.json',{cache:'no-store'});if(!r.ok)throw new Error('Base prix indisponible');db=await r.json();renderNeed();}
  function setStep(n){$$('.quote-step').forEach((e,i)=>e.classList.toggle('is-active',i===n));}
  function product(id){return db.products.find(p=>p.id===id);}
  function renderNeed(){setStep(0);$('#quote-view').innerHTML=`<div class="quote-view"><div class="view-kicker">27SYS / ESTIMATION ÉQUIPEMENTS</div><h2 class="view-title">Quel projet voulez-vous chiffrer ?</h2><p class="view-sub">Le simulateur adapte ensuite les équipements proposés à votre situation. Vous pourrez modifier les quantités avant de demander le coût d'installation.</p><div class="option-grid">
    <button class="option" data-project="home"><strong>Maison / particulier</strong><span>Wi-Fi, routeur, stockage, impression et protection électrique.</span></button>
    <button class="option" data-project="office"><strong>Bureau / petite entreprise</strong><span>Postes, réseau, Wi-Fi, impression et continuité électrique.</span></button>
    <button class="option" data-project="network"><strong>Réseau / Wi-Fi</strong><span>Routeur, switch, points d'accès et capacité de connexion.</span></button>
    <button class="option" data-project="upgrade"><strong>PC / upgrade</strong><span>SSD et équipement de base pour améliorer une machine existante.</span></button>
  </div></div>`;$$('.option').forEach(b=>b.addEventListener('click',()=>{state.project=b.dataset.project;renderConfig();}));}
  function renderConfig(){setStep(1);const isOffice=state.project==='office';$('#quote-view').innerHTML=`<div class="quote-view"><div class="view-kicker">27SYS / CONFIGURATION</div><h2 class="view-title">Définissez votre besoin.</h2><p class="view-sub">Ces réponses servent à construire une première liste d'équipements. Rien n'est commandé automatiquement.</p><div class="form-grid">
    <div class="field"><label for="pcs">POSTES À ÉQUIPER</label><input id="pcs" type="number" min="0" max="100" value="${isOffice?5:1}"><small>PC fixes ou portables nécessitant un équipement.</small></div>
    <div class="field"><label for="wifi">COUVERTURE WI-FI</label><select id="wifi"><option value="none">Pas de point d'accès supplémentaire</option><option value="standard" selected>Couverture standard</option><option value="large">Grande surface / plusieurs zones</option></select></div>
    <div class="field"><label for="printer">IMPRESSION</label><select id="printer"><option value="none">Aucune</option><option value="laser">Laser monochrome</option><option value="tank">Couleur / réservoir</option></select></div>
    <div class="field"><label for="ups">ONDULEUR</label><select id="ups"><option value="none">Aucun</option><option value="one">1 onduleur central</option></select></div>
    <div class="field"><label for="storage">STOCKAGE / UPGRADE</label><select id="storage"><option value="none">Aucun</option><option value="ssd">1 SSD 500 Go environ</option><option value="ssdx2">2 SSD 500 Go environ</option></select></div>
    <div class="field"><label for="cable">CÂBLAGE RJ45</label><select id="cable"><option value="0">Pas de câblage à estimer</option><option value="25">25 m</option><option value="50">50 m</option><option value="100">100 m</option><option value="200">200 m</option></select></div>
  </div><div class="quote-actions"><button class="btn" id="back-project">← Retour</button><button class="btn btn-primary" id="build">Générer l'estimation →</button></div></div>`;$('#back-project').addEventListener('click',renderNeed);$('#build').addEventListener('click',buildQuote);}
  function buildQuote(){const pcs=Number($('#pcs').value)||0,wifi=$('#wifi').value,printerChoice=$('#printer').value,ups=$('#ups').value,storage=$('#storage').value,cable=Number($('#cable').value)||0;const wired=Math.max(pcs,0);let routerId='router-c6';if(pcs>25)routerId='router-ax73';else if(pcs>12)routerId='router-ax23';const ids=[];if(state.project!=='upgrade')ids.push([routerId,1,'Base réseau recommandée']);
    if(wired>0){const qty=Math.max(1,Math.ceil((wired+2)/8));ids.push(['switch-ls1008g',qty,`${wired} poste(s) filaire(s) + marge`]);}
    if(wifi==='standard')ids.push(['ap-eap650',1,'Couverture Wi-Fi standard']);
    if(wifi==='large')ids.push(['ap-eap650',2,'Deux zones / grande surface']);
    if(printerChoice==='laser')ids.push(['printer-canon-lbp6030w',1,'Impression laser']);
    if(printerChoice==='tank')ids.push(['printer-hp-smart-tank-585',1,'Impression couleur / réservoir']);
    if(ups==='one')ids.push(['ups-apc-bx1600',1,'Protection électrique centrale']);
    if(storage==='ssd')ids.push(['ssd-nv2-500',1,'Upgrade stockage']);
    if(storage==='ssdx2')ids.push(['ssd-nv2-500',2,'Upgrade stockage']);
    if(state.project==='office'&&pcs>0)ids.push(['laptop-hp-15',pcs,'Poste bureautique indicatif']);
    if(state.project==='upgrade')ids.push(['ssd-a400-480',1,'Upgrade SSD SATA indicatif']);
    state.config={pcs,wifi,printer:printerChoice,ups,storage,cable};state.items=ids;renderQuote(cable);}
  function renderQuote(cable){setStep(2);const rows=state.items.map(([id,qty,reason])=>{const p=product(id);return `<div class="quote-row" data-id="${esc(id)}"><div class="quote-name"><strong>${esc(p.name)}</strong><span>${esc(reason)}</span></div><div class="qty-control"><button type="button" data-act="minus">−</button><output>${qty}</output><button type="button" data-act="plus">+</button></div><div>${money(p.price*qty)}</div><a class="source-link" href="${esc(p.url)}" target="_blank" rel="noopener">${esc(p.source)} ↗</a></div>`}).join('');let total=state.items.reduce((sum,[id,qty])=>sum+product(id).price*qty,0);const cableCost=cable*4; if(cable>0)total+=cableCost;$('#quote-view').innerHTML=`<div class="quote-view"><div class="view-kicker">27SYS / BUDGET INDICATIF</div><h2 class="view-title">Votre estimation équipements</h2><p class="view-sub">Les quantités restent modifiables. Le total ci-dessous concerne les équipements suivis, pas la main-d'œuvre.</p><div class="quote-table"><div class="quote-row header"><div>Équipement</div><div>Qté</div><div>Total</div><div>Source</div></div>${rows}${cable>0?`<div class="quote-row"><div class="quote-name"><strong>Câblage Cat6 — estimation</strong><span>${cable} m × 4 DH/m, à confirmer selon le type de câble et le chantier</span></div><div>${cable} m</div><div>${money(cableCost)}</div><div class="source-link">Indicatif</div></div>`:''}</div><div class="total-card"><div><b>TOTAL ÉQUIPEMENTS</b><strong>${money(total)}</strong><p class="install-note"><strong>Installation : non incluse.</strong> Le coût dépend du nombre de postes, du câblage, de la configuration et de l'intervention.</p></div><button class="btn btn-primary" id="ask-install">Demander le devis d'installation ↗</button></div><div class="price-note"><strong>Prix marché.</strong> Valeurs indicatives et non garanties : disponibilité, vendeur, garantie, livraison et modèle exact peuvent modifier le prix. Les produits avec mise à jour automatique sont contrôlés par le flux quotidien de 27sys.</div><div class="quote-actions"><button class="btn" id="edit-config">← Modifier mes besoins</button><button class="btn btn-blue" id="copy-quote">Copier l'estimation</button></div></div>`;
    $$('.quote-row[data-id]').forEach(row=>row.querySelectorAll('[data-act]').forEach(btn=>btn.addEventListener('click',()=>changeQty(row.dataset.id,btn.dataset.act,cable))));$('#edit-config').addEventListener('click',renderConfig);$('#copy-quote').addEventListener('click',async()=>{await navigator.clipboard?.writeText(buildText(cable,total));$('#copy-quote').textContent='Copié ✓';});$('#ask-install').addEventListener('click',()=>openWhatsApp(cable,total));}
  function changeQty(id,act,cable){const item=state.items.find(x=>x[0]===id);if(!item)return;item[1]=Math.max(0,Math.min(100,item[1]+(act==='plus'?1:-1)));if(item[1]===0)state.items=state.items.filter(x=>x!==item);renderQuote(cable);}
  function buildText(cable,total){const lines=state.items.map(([id,q])=>`• ${q} × ${product(id).name} = ${money(product(id).price*q)}`);if(cable>0)lines.push(`• ${cable} m × câble Cat6 indicatif = ${money(cable*4)}`);return `DEVIS ÉQUIPEMENTS 27SYS\n\n${lines.join('\n')}\n\nTOTAL ÉQUIPEMENTS : ${money(total)}\nInstallation : à chiffrer par 27sys après échange.\nPrix indicatifs — disponibilité et modèle à confirmer.`;}
  function openWhatsApp(cable,total){const text=`Bonjour 27sys,\n\nJe viens de terminer le simulateur de devis.\n\n${buildText(cable,total)}\n\nJe souhaite connaître le coût d'installation et vérifier la configuration.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(text)}`,'_blank','noopener');}
  load().catch(err=>{$('#quote-view').innerHTML=`<div class="tree-empty">Impossible de charger les prix pour le moment. Rechargez la page ou contactez 27sys sur WhatsApp.</div>`;console.error(err);});
})();
